"""
Feast Data Source Definitions — RecoStack

Each data source points to a Parquet file on the local filesystem.
These files are generated by scripts/generate_feature_data.py and
contain pre-computed features for users, movies, and interactions.
"""

from pathlib import Path

from feast.infra.offline_stores.file_source import FileSource

# Root directory for feature Parquet files
FEATURES_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "features"

# ---------------------------------------------------------------------------
# User stats data source
# ---------------------------------------------------------------------------
user_stats_source = FileSource(
    name="user_stats_source",
    path=str(FEATURES_DIR / "user_stats.parquet"),
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# ---------------------------------------------------------------------------
# Movie stats data source
# ---------------------------------------------------------------------------
movie_stats_source = FileSource(
    name="movie_stats_source",
    path=str(FEATURES_DIR / "movie_stats.parquet"),
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# ---------------------------------------------------------------------------
# User-movie interaction data source (raw ratings)
# ---------------------------------------------------------------------------
interaction_source = FileSource(
    name="interaction_source",
    path=str(FEATURES_DIR / "interactions.parquet"),
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)